# Generated by Django 4.0.2 on 2022-02-09 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_add_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_id',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
